### ISSUE TITLE
Game does not start when playing against AI. 

### ISSUE THREAD

**Issue by KPLauritzen** [Pixel-Pox/checkers#3]
When I un-comment these lines in `main.py`
```python
        if not game.is_won() or not game.is_tie():
            if game.turn == BLACK:
                _, new_board = minimax(game, 3, False, float('-inf'), float('inf'))
                game.ai_move(new_board)

            else:          
                _, new_board = minimax(game, 3, True, float('-inf'), float('inf'))
                game.ai_move(new_board)
```
the game does not start.

I get this error
```text
Traceback (most recent call last):
  File "C:\Users\Kasper\dev\checkers\main.py", line 55, in <module>
    main()
  File "C:\Users\Kasper\dev\checkers\main.py", line 29, in main
    _, new_board = minimax(game, 3, True, float('-inf'), float('inf'))
  File "C:\Users\Kasper\dev\checkers\minimax\algorithm.py", line 19, in minimax
    for move in get_all_moves(board, WHITE):
  File "C:\Users\Kasper\dev\checkers\minimax\algorithm.py", line 72, in get_all_moves
    for move, skip in valid_moves.items():
AttributeError: 'tuple' object has no attribute 'items'
```

**Comment by Pixel-Pox** [comment]
Fixed now :)
Thanks
